# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-02 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0002_auto_20180204_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_column='Code', max_length=20)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=50, null=True)),
                ('changes', models.CharField(blank=True, db_column='Changes', max_length=50, null=True)),
                ('language', models.CharField(blank=True, db_column='Language', max_length=50, null=True)),
                ('credit', models.IntegerField(blank=True, db_column='Credit', null=True)),
                ('size', models.IntegerField(blank=True, db_column='Size', null=True)),
                ('p1', models.IntegerField(blank=True, db_column='P1', null=True)),
                ('p2', models.IntegerField(blank=True, db_column='P2', null=True)),
                ('p3', models.IntegerField(blank=True, db_column='P3', null=True)),
                ('p4', models.IntegerField(blank=True, db_column='P4', null=True)),
                ('p5', models.IntegerField(blank=True, db_column='P5', null=True)),
                ('total', models.IntegerField(blank=True, db_column='Total', null=True)),
                ('curriculumid', models.IntegerField()),
            ],
            options={
                'db_table': 'course',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_column='Name', max_length=50, null=True)),
                ('degreeprogramid', models.IntegerField()),
            ],
            options={
                'db_table': 'curriculum',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Degreeprogram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_column='Code', max_length=50, unique=True)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=50, null=True)),
            ],
            options={
                'db_table': 'degreeprogram',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Implementation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseid', models.IntegerField()),
            ],
            options={
                'db_table': 'implementation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_column='Code', max_length=20, unique=True)),
                ('seats', models.IntegerField(blank=True, db_column='Seats', null=True)),
                ('topic', models.CharField(blank=True, db_column='Topic', max_length=50, null=True)),
            ],
            options={
                'db_table': 'room',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoomImplementation',
            fields=[
                ('implementationid', models.IntegerField(primary_key=True, serialize=False)),
                ('roomid', models.IntegerField()),
            ],
            options={
                'db_table': 'room_implementation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subgroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, db_column='Code', max_length=20, null=True)),
                ('department', models.CharField(blank=True, db_column='Department', max_length=50, null=True)),
                ('groupid', models.IntegerField()),
                ('degreeprogramid', models.IntegerField()),
            ],
            options={
                'db_table': 'subgroup',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubgroupImplementation',
            fields=[
                ('subgroupid', models.IntegerField(primary_key=True, serialize=False)),
                ('implementationid', models.IntegerField()),
            ],
            options={
                'db_table': 'subgroup_implementation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_column='Code', max_length=10, unique=True)),
                ('name', models.CharField(db_column='Name', max_length=50, unique=True)),
            ],
            options={
                'db_table': 'teacher',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeacherDegreeprogram',
            fields=[
                ('degreeprogramid', models.IntegerField(primary_key=True, serialize=False)),
                ('teacherid', models.IntegerField()),
            ],
            options={
                'db_table': 'teacher_degreeprogram',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeacherImplementation',
            fields=[
                ('teacherid', models.IntegerField(primary_key=True, serialize=False)),
                ('implementationid', models.IntegerField()),
            ],
            options={
                'db_table': 'teacher_implementation',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='city',
            name='countryid',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cityid',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
